services:
  - type: web
    name: spam-detection-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python test_app.py
    healthCheckPath: /ping
    envVars:
      - key: PORT
        value: 8000